steps:
#This is just a tests
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build test container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/api_image_test',
    '--progress=plain',
    '-f',
    'cloud_test/cloud_test.dockerfile'
  ] 

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push test container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/api_image_test'
  ]

#This part builds and deploys the actual api
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build api container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/api_image',
    '--progress=plain',
    '-f',
    'dockerfiles/api.dockerfile'
  ] 

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push api container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/api_image'
  ]



options:
  logging: CLOUD_LOGGING_ONLY