steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - "-t"
    - "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/train"
    - "dockerfiles/train.dockerfile"
    - "."
#- name: 'gcr.io/cloud-builders/docker'
#  args:
#    - build
#    - "-t"
#    - "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/evaluate"
#    - "--file=path/to/Dockerfile2"
#    - "."
# Add more steps as needed for additional Dockerfiles...

images:
  - "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/train"
  
#- "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/image2"
# Add more image names as needed for additional Dockerfiles.

options:
  logging: CLOUD_LOGGING_ONLY