steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - "-t"
    - "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/train-image"
    - "--progress=plain"  # Enables detailed build logs
    - "--no-cache"        # Forces a clean build
    - "dockerfiles/train.dockerfile"
    - "."
#- name: 'gcr.io/cloud-builders/docker'
#  args:
#    - build
#    - "-t"
#    - "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/evaluate"
#    - "--file=path/to/Dockerfile2"
#    - "."
# Add more steps as needed for additional Dockerfiles...

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/train-image'
  ]
  
#- "europe-west1-docker.pkg.dev/quickdrawproject-448508/quickdraw-artifacts/image2"
# Add more image names as needed for additional Dockerfiles.

options:
  logging: CLOUD_LOGGING_ONLY