program: src/quick_draw/train_wandb.py
name: ml_ops_02476
project: sweep_demo  # the project name
entity: ml_ops_02476  # the team
metric:
    goal: minimize
    name: validation_loss
method:
  bayes
parameters:
    lr:
      values: [0.001, 0.0001]
    batch-size:
      values: [16, 32, 64]
    epochs:
      values: [5, 10]
run_cap: 10


# To run sweep:
# wandb sweep configs/sweep.yaml
# Get run id
# wandb agent ml_ops_02476/sweepdemo1/fa8wtttl
# sweepdemo1 has to be the "project" above. fa8wtttl is the run id.
