site_name: quick draw mlops
site_author: Christiansen, Eriksen, Hyllinge, Mondrup, Schmidt
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_root_heading: false
            separate_signature: true
            show_signature_annotations: true
            show_source: true


nav:
  - Home: index.md
  - model: my_api.md
