name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        #operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        operating-system: ["ubuntu-latest"]
        #python-version: ["3.11", "3.12"]
        python-version: ["3.11"]

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python with cache
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # 3. Install dependencies (split production and dev dependencies)
      - name: Install production dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Install development dependencies
        run: |
          pip install -r requirements_dev.txt

      # 4. Set PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      # 6. Run tests and coverage
      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -i
